### ISSUE TITLE
HazelcastIntegrationTest.testIntegration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-zookeeper#4]
```
java.lang.IllegalStateException: Error while talking to ZooKeeper. 
    at com.hazelcast.zookeeper.HazelcastIntegrationTest.testIntegration(HazelcastIntegrationTest.java:41)
Caused by: java.net.SocketException: No such device
    at com.hazelcast.zookeeper.HazelcastIntegrationTest.testIntegration(HazelcastIntegrationTest.java:41)
```

https://hazelcast-l337.ci.cloudbees.com/view/Plugins/job/Zookeeper/18/com.hazelcast$hazelcast-zookeeper/testReport/com.hazelcast.zookeeper/HazelcastIntegrationTest/testIntegration/

**Comment by jerrinot** [comment]
now this a very nice failure! `Caused by: java.net.SocketException: No such device`

**Comment by lazerion** [comment]
`no failure since 10/2016` closing after discussion with originator
