### ISSUE TITLE
Can't get Hazelcast to connect to Zookeeper

### ISSUE THREAD

**Issue by oliversalmon** [hazelcast/hazelcast-zookeeper#5]
Hi,
I seem to be having a problem where Hazelcast starts normally but doesn't connect to Zookeeper so if I start another Hz node it thinks it's in a cluster of one. 
The following is an section of the  log from Zookeeper so it looks like Hazelcast is trying to connect

2016-10-26 07:04:22,760 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@673] - Established session 0x157fdcee7fc0001 with negotiated timeout 40000 for client /172.17.0.1:60102
2016-10-26 07:04:22,763 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@735] - Received packet at server of unknown type 15
2016-10-26 07:04:22,764 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /172.17.0.1:60102 which had sessionid 0x157fdcee7fc0001
2016-10-26 07:04:23,216 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /172.17.0.1:60104
2016-10-26 07:04:23,217 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@921] - Client attempting to renew session 0x157fdcee7fc0001 at /172.17.0.1:60104
2016-10-26 07:04:23,219 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@673] - Established session 0x157fdcee7fc0001 with negotiated timeout 40000 for client /172.17.0.1:60104
2016-10-26 07:04:23,222 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@735] - Received packet at server of unknown type 15
2016-10-26 07:04:23,224 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /172.17.0.1:60104 which had sessionid 0x157fdcee7fc0001

Also get this 

2016-10-26 07:11:32,012 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x157fdcee7fc0002 type:delete cxid:0x15 zxid:0x8 txntype:-1 reqpath:n/a Error Path:/discovery/hazelcast/kappa-serving-layer Error:KeeperErrorCode = NoNode for /discovery/hazelcast/kappa-serving-layer
2016-10-26 07:11:32,025 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@487] - Processed session termination for sessionid: 0x157fdcee7fc0002
2016-10-26 07:11:32,032 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /172.17.0.1:60136 which had sessionid 0x157fdcee7fc0002

This is the network section of my cache configuration file

```
<network>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false" />
            <aws enabled="false"/>
            <discovery-strategies>
                <discovery-strategy enabled="true" class="com.hazelcast.zookeeper.ZookeeperDiscoveryStrategy">
                    <properties>
                        <!--
                          Connection string to your ZooKeeper server.
                          Default: There is no default, this is a required property.
                          Example: 127.0.0.1:2181
                        -->
                        <property name="zookeeper_url">localhost:2181</property>
                        <!--Path in ZooKeeper Hazelcast will useDefault: /discovery/hazelcast -->
                        <property name="zookeeper_path">/discovery/hazelcast</property>
                        <!--Name of this Hazelcast cluster. You can have multiple distinct clusters to use the same ZooKeeper installation.-->
                        <property name="group">kappa-serving-layer</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
```

Zookeeper is running in a Docker container exposing 2818 to local host as 2181 and is contactable.

I'm new to zookeeper, any ideas?
Thanks very much in advance for your help,
Oliver

**Comment by bilalyasar** [comment]
@oliversalmon what is your zookeeper version? or what is your docker image/tag? So i can try to reproduce your scenario.

**Comment by oliversalmon** [comment]
Hi,
I'm using the latest Zookeeper from here [https://hub.docker.com/_/zookeeper/](url)
I used `docker run --name some-zookeeper --restart always -d zookeeper` to create the container
2181/tcp	localhost:2181
2888/tcp	localhost:2888
3888/tcp	localhost:3888
Are the exposed ports.
Thanks for helping.
Oliver

**Comment by oliversalmon** [comment]
Forgot to say that Hazelcast isn't running in a container.
Cheers

**Comment by oliversalmon** [comment]
I'm running Hz on a Mac, I've noticed some networking issues when trying to connect to Couchbase through the Java SDK as well where the socket seems to close immediately after the first operation. Does anyone have any idea if it's OSX causing these problems and if so hw to fix or work around them?
Thanks.

**Comment by oliversalmon** [comment]
Running Hazelcast and Zookeeper in containers now and it still won't create the cluster

**Comment by neilstevenson** [comment]
@oliversalmon On Sierra ?

**Comment by noctarius** [comment]
Isn't it that both docker containers should have different IP addresses?

**Comment by oliversalmon** [comment]
Hi,
Neil, I'm on El Cap at the moment not Sierra.
Noctarius, that Hazelcast config snippet is from when I had Hazelcast running directly under OSX with Zookeeper in a container. Changed the ip address in `<property name="zookeeper_url">localhost:2181</property>` to the actual ip address of the mac when running Hz in a container as well, also tried 0.0.0.0, still no joy.
Do I need to link the containers or use docker-compose?

**Comment by oliversalmon** [comment]
Tried bring them all up with docker compose (2 Hz containers 1 Zookeeper) including links between the containers, still not working.
Here's my docker-compose
```
version: '2'
services:
  zookeeper:
    image: zookeeper
    links:
      - kappahz1
      - kappahz2
    ports:
      - "2181:2181"

  kappahz1:
    build: .

  kappahz2:
    build: .
    ports:
      - "5701:5701"
```

**Comment by oliversalmon** [comment]
Hi,
Have moved everything to Digital Ocean now.
Am running zookeeper on its own server using
`docker run --name some-zookeeper --restart always -d zookeeper`
Using the following docker image for Hz nodes on their own server
`olibs/kappahz`
The docker file for the image is
```
FROM hazelcast/hazelcast:v2
# Add custom hazelcast.xml
ADD sandpit-cache-config.xml $HZ_HOME
# Add application jars
ADD domain-1.0-SNAPSHOT.jar $HZ_HOME
ADD datagrid-1.0-SNAPSHOT.jar $HZ_HOME
# Add custom script to start Hz using all the jars and the config
ADD startHz.sh $HZ_HOME
# Add all the zookeeper and curator dependencies
COPY ./lib $HZ_HOME/lib
RUN chmod 755 $HZ_HOME/startHz.sh

# Run hazelcast
CMD ./startHz.sh
```
The network section of the Hz config is
```
<network>
        <join>
            <multicast enabled="false"/>
            <tcp-ip enabled="false" />
            <aws enabled="false"/>
            <discovery-strategies>
                <discovery-strategy enabled="true" class="com.hazelcast.zookeeper.ZookeeperDiscoveryStrategy">
                    <properties>
                        <!--
                          Connection string to your ZooKeeper server.
                          Default: There is no default, this is a required property.
                          Example: 127.0.0.1:2181
                        -->
                        <property name="zookeeper_url">138.68.172.212:2181</property>
                        <!--Path in ZooKeeper Hazelcast will useDefault: /discovery/hazelcast -->
                        <property name="zookeeper_path">/discovery/hazelcast</property>
                        <!--Name of this Hazelcast cluster. You can have multiple distinct clusters to use the same ZooKeeper installation.-->
                        <property name="group">kappa-serving-layer</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
```
My original error has gone away, I assume this was a mac issue, but now I get the following in the Hz node log when I run the image
`docker run -p5701:5701 -d --name hzkappa1 olibs/kappahz:v2`

```
root@mu-architecture-servinglayer:~# docker logs hzkappa1
Oct 31, 2016 6:43:57 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading configuration /opt/hazelcast/sandpit-cache-config.xml from System property 'hazelcast.config'
Oct 31, 2016 6:43:57 AM com.hazelcast.config.XmlConfigLocator
INFO: Using configuration file at /opt/hazelcast/sandpit-cache-config.xml
Oct 31, 2016 6:43:58 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [kappa-serving-layer] [3.7.1] Prefer IPv4 stack is true.
Oct 31, 2016 6:43:58 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [kappa-serving-layer] [3.7.1] Picked [172.17.0.2]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Oct 31, 2016 6:43:58 AM com.hazelcast.system
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Hazelcast 3.7.1 (20160905 - 1f47990) starting at [172.17.0.2]:5701
Oct 31, 2016 6:43:58 AM com.hazelcast.system
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
Oct 31, 2016 6:43:58 AM com.hazelcast.system
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Configured Hazelcast Serialization version : 1
Oct 31, 2016 6:43:58 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Backpressure is disabled
Oct 31, 2016 6:43:58 AM com.hazelcast.instance.Node
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Activating Discovery SPI Joiner
Oct 31, 2016 6:43:58 AM com.hazelcast.core.LifecycleService
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] [172.17.0.2]:5701 is STARTING
Oct 31, 2016 6:43:59 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Starting 4 partition threads
Oct 31, 2016 6:43:59 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Starting 3 generic threads (1 dedicated for priority tasks)
Oct 31, 2016 6:43:59 AM com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
log4j:WARN No appenders could be found for logger (org.apache.curator.framework.imps.CuratorFrameworkImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 31, 2016 6:44:41 AM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
SEVERE: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Error while talking to ZooKeeper
java.lang.IllegalStateException: Error while talking to ZooKeeper
	at com.hazelcast.zookeeper.ZookeeperDiscoveryStrategy.discoverNodes(ZookeeperDiscoveryStrategy.java:132)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:43)
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:135)
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:93)
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
	at com.hazelcast.instance.Node.join(Node.java:650)
	at com.hazelcast.instance.Node.start(Node.java:362)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /discovery/hazelcast/kappa-serving-layer
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2373)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:234)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:223)
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:67)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:99)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:219)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:211)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:41)
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.queryForInstances(ServiceDiscoveryImpl.java:382)
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.queryForInstances(ServiceDiscoveryImpl.java:306)
	at com.hazelcast.zookeeper.ZookeeperDiscoveryStrategy.discoverNodes(ZookeeperDiscoveryStrategy.java:116)
	... 13 more

Oct 31, 2016 6:44:41 AM com.hazelcast.instance.Node
SEVERE: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Could not join cluster in 300000 ms. Shutting down now!
Oct 31, 2016 6:44:41 AM com.hazelcast.core.LifecycleService
INFO: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] [172.17.0.2]:5701 is SHUTTING_DOWN
Oct 31, 2016 6:44:41 AM com.hazelcast.instance.Node
WARNING: [172.17.0.2]:5701 [kappa-serving-layer] [3.7.1] Terminating forcefully...
```
@neilstevenson or @noctarius any ideas? I'm completely stuck and really want to get this to work.

Thanks again for all your help,
Oliver

**Comment by bilalyasar** [comment]
@oliversalmon , I have tried your zookeeper and hazelcast image. The zookeeper image gives following error.
```
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
mkdir: can't create directory '': No such file or directory
2016-10-31 09:38:17,985 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /conf/zoo.cfg
2016-10-31 09:38:17,988 [myid:] - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /conf/zoo.cfg
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:144)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.IllegalArgumentException: dataDir is not set
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:264)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:140)
	... 2 more
Invalid config, exiting abnormally
```

**Comment by oliversalmon** [comment]
@bilalyasar thanks for trying, that's odd I don't get that either locally or on DigitalOcean, here my log from DO
```
root@mu-architecture-zookeeper:~# docker logs some-zookeeper
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
2016-10-31 06:30:15,723 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /conf/zoo.cfg
2016-10-31 06:30:15,729 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2016-10-31 06:30:15,730 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2016-10-31 06:30:15,730 [myid:] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2016-10-31 06:30:15,731 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
2016-10-31 06:30:15,760 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /conf/zoo.cfg
2016-10-31 06:30:15,760 [myid:] - INFO  [main:ZooKeeperServerMain@96] - Starting server
2016-10-31 06:30:15,771 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
2016-10-31 06:30:15,771 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=083812974c7e
2016-10-31 06:30:15,771 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.8.0_92-internal
2016-10-31 06:30:15,772 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
2016-10-31 06:30:15,772 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-1.8-openjdk/jre
2016-10-31 06:30:15,772 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/zookeeper-3.4.9/bin/../build/classes:/zookeeper-3.4.9/bin/../build/lib/*.jar:/zookeeper-3.4.9/bin/../lib/slf4j-log4j12-1.6.1.jar:/zookeeper-3.4.9/bin/../lib/slf4j-api-1.6.1.jar:/zookeeper-3.4.9/bin/../lib/netty-3.10.5.Final.jar:/zookeeper-3.4.9/bin/../lib/log4j-1.2.16.jar:/zookeeper-3.4.9/bin/../lib/jline-0.9.94.jar:/zookeeper-3.4.9/bin/../zookeeper-3.4.9.jar:/zookeeper-3.4.9/bin/../src/java/lib/*.jar:/conf:
2016-10-31 06:30:15,772 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2016-10-31 06:30:15,773 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
2016-10-31 06:30:15,773 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
2016-10-31 06:30:15,774 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
2016-10-31 06:30:15,774 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2016-10-31 06:30:15,775 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.4.0-45-generic
2016-10-31 06:30:15,775 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=zookeeper
2016-10-31 06:30:15,775 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/home/zookeeper
2016-10-31 06:30:15,775 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/zookeeper-3.4.9
2016-10-31 06:30:15,785 [myid:] - INFO  [main:ZooKeeperServer@815] - tickTime set to 2000
2016-10-31 06:30:15,785 [myid:] - INFO  [main:ZooKeeperServer@824] - minSessionTimeout set to -1
2016-10-31 06:30:15,785 [myid:] - INFO  [main:ZooKeeperServer@833] - maxSessionTimeout set to -1
2016-10-31 06:30:15,802 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
```
Thanks again for your help

**Comment by oliversalmon** [comment]
Hi @bilalyasar 
Realised that I hadn't mapped the exposed zookeeper ports!
Still with that fixed I still can't get the Hz nodes to form a cluster.
The log just shows 
```
Oct 31, 2016 7:43:37 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading configuration /opt/hazelcast/sandpit-cache-config.xml from System property 'hazelcast.config'
Oct 31, 2016 7:43:37 PM com.hazelcast.config.XmlConfigLocator
INFO: Using configuration file at /opt/hazelcast/sandpit-cache-config.xml
Oct 31, 2016 7:43:38 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [kappa-serving-layer] [3.7.1] Prefer IPv4 stack is true.
Oct 31, 2016 7:43:38 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [kappa-serving-layer] [3.7.1] Picked [172.17.0.3]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Oct 31, 2016 7:43:38 PM com.hazelcast.system
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Hazelcast 3.7.1 (20160905 - 1f47990) starting at [172.17.0.3]:5701
Oct 31, 2016 7:43:38 PM com.hazelcast.system
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
Oct 31, 2016 7:43:38 PM com.hazelcast.system
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Configured Hazelcast Serialization version : 1
Oct 31, 2016 7:43:38 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Backpressure is disabled
Oct 31, 2016 7:43:39 PM com.hazelcast.instance.Node
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Activating Discovery SPI Joiner
Oct 31, 2016 7:43:39 PM com.hazelcast.core.LifecycleService
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] [172.17.0.3]:5701 is STARTING
Oct 31, 2016 7:43:39 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Starting 4 partition threads
Oct 31, 2016 7:43:39 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] Starting 3 generic threads (1 dedicated for priority tasks)
Oct 31, 2016 7:43:39 PM com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
log4j:WARN No appenders could be found for logger (org.apache.curator.framework.imps.CuratorFrameworkImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 31, 2016 7:43:41 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] 


Members [1] {
	Member [172.17.0.3]:5701 - e26947b5-5b14-49ab-bd64-4ab7b99219b5 this
}

Oct 31, 2016 7:43:41 PM com.hazelcast.core.LifecycleService
INFO: [172.17.0.3]:5701 [kappa-serving-layer] [3.7.1] [172.17.0.3]:5701 is STARTED
```

Zookeeper is definitely up and running as I have Kafka talking to it from another server.

Thanks again for you help and sorry about the mistake above.
Oliver

**Comment by bilalyasar** [comment]
@oliversalmon can you write your latest docker commands?

**Comment by oliversalmon** [comment]
@bilalyasar 
Hi, 
I'm just running Hz on it's own server now so
```
docker run -p 5701:5701 --name muhz1 -t -i -d olibs/kappahz:v4

docker run --name muhz2 -t -i -d olibs/kappahz:v4
```
The zookeeper instance that the config file is pointing to is on the internet so you should be able to connect to it.
Thanks again for your help,
Oliver

**Comment by bilalyasar** [comment]
now i am getting this error from zookeeper.
```
2016-11-02 09:15:17,296 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@617] - Established session 0x158244fbb960001 with negotiated timeout 40000 for client /172.30.0.14:47547
2016-11-02 09:15:17,297 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@675] - Received packet at server of unknown type 15
2016-11-02 09:15:17,297 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /172.30.0.14:47547 which had sessionid 0x158244fbb960001
2016-11-02 09:15:17,796 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /172.30.0.14:47548
```

` Received packet at server of unknown type 15`

By the way, i have changed zookeeper url in hazelcast.xml

**Comment by oliversalmon** [comment]
@bilalyasar 
Hi that looks like the issue I had a the start when I was running the hazelcast nodes on my Mac.
From above
```
[NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@921] - Client attempting to renew session 0x157fdcee7fc0001 at /172.17.0.1:60104
2016-10-26 07:04:23,219 [myid:] - INFO [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@673] - Established session 0x157fdcee7fc0001 with negotiated timeout 40000 for client /172.17.0.1:60104
2016-10-26 07:04:23,222 [myid:] - WARN [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@735] - Received packet at server of unknown type 15
2016-10-26 07:04:23,224 [myid:] - INFO [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /172.17.0.1:60104 which had sessionid 0x157fdcee7fc0001
```
What changes did you make to the zookeeper url?
Thanks,
Oliver

**Comment by bilalyasar** [comment]
I changed as ` <property name="zookeeper_url">0.0.0.0:2181</property>`
it was another different ip.
Also i am starting hazelcast instances as:
`docker run -it --net=host zookeeper`
`docker run -p 5701:5701 --net=host -t -i -d hzhz`   ( actually no need to port expose when we use `--net=host` )

**Comment by oliversalmon** [comment]
OK, I currently have Zookeeeper and Hz on different servers
HZ on 138.68.164.125
Zookeeper on 138.68.172.212
Zookeeper is definitely reachable as I have Kafka running on 138.68.135.220 and it is connecting to zookeeper.
Any idea what the packet issues are ?
Thanks,
Oliver

**Comment by bilalyasar** [comment]
it may be incompatibility between zookeeper and hazelcast curator client. I am trying to analyze the issue.

**Comment by oliversalmon** [comment]
Thanks

**Comment by michaeljs1990** [comment]
This is an issue between the hazelcast and curator client. I was able to get this working using the dependencies as described in the pom.xml file. You can also see another person who had the exact same issue here https://github.com/rahulsh1/zoocurator.

**Comment by oliversalmon** [comment]
@michaeljs1990 
Thanks very much for your help, I'll give it a go.

**Comment by oliversalmon** [comment]
@bilalyasar @neilstevenson @michaeljs1990 
Thanks very much for all your help guys, that fixed the problem now have a cluster running happily!

**Comment by bilalyasar** [comment]
@oliversalmon , Can you explain more detailed how you solved the issue? Then i can update readme.

**Comment by oliversalmon** [comment]
Hi,
I just updated my pom to use the same curator jar versions as https://github.com/rahulsh1/zoocurator.
And it all suddenly worked.
Now I can start docker containers they discover and join the cluster through zookeeper

**Comment by michaeljs1990** [comment]
It also works if you just use the pom.xml file from this repo.
